CREATE TABLE IF NOT EXISTS city(
   id          INTEGER  NOT NULL PRIMARY KEY
  ,title        VARCHAR(17) NOT NULL
  ,slug        VARCHAR(26)
  ,provinceId INTEGER  NOT NULL
);
INSERT INTO city(id,title,slug,provinceId) VALUES (1,'اسکو','اسکو',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (2,'اهر','اهر',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (3,'ایلخچی','ایلخچی',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (4,'آبش احمد','آبش-احمد',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (5,'آذرشهر','آذرشهر',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (6,'آقکند','آقکند',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (7,'باسمنج','باسمنج',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (8,'بخشایش','بخشایش',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (9,'بستان آباد','بستان-آباد',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (10,'بناب','بناب',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (11,'بناب جدید','بناب-جدید',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (12,'تبریز','تبریز',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (13,'ترک','ترک',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (14,'ترکمانچای','ترکمانچای',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (15,'تسوج','تسوج',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (16,'تیکمه داش','تیکمه-داش',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (17,'جلفا','جلفا',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (18,'خاروانا','خاروانا',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (19,'خامنه','خامنه',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (20,'خراجو','خراجو',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (21,'خسروشهر','خسروشهر',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (22,'خضرلو','خضرلو',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (23,'خمارلو','خمارلو',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (24,'خواجه','خواجه',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (25,'دوزدوزان','دوزدوزان',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (26,'زرنق','زرنق',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (27,'زنوز','زنوز',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (28,'سراب','سراب',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (29,'سردرود','سردرود',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (30,'سهند','سهند',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (31,'سیس','سیس',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (32,'سیه رود','سیه-رود',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (33,'شبستر','شبستر',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (34,'شربیان','شربیان',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (35,'شرفخانه','شرفخانه',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (36,'شندآباد','شندآباد',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (37,'صوفیان','صوفیان',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (38,'عجب شیر','عجب-شیر',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (39,'قره آغاج','قره-آغاج',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (40,'کشکسرای','کشکسرای',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (41,'کلوانق','کلوانق',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (42,'کلیبر','کلیبر',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (43,'کوزه کنان','کوزه-کنان',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (44,'گوگان','گوگان',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (45,'لیلان','لیلان',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (46,'مراغه','مراغه',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (47,'مرند','مرند',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (48,'ملکان','ملکان',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (49,'ملک کیان','ملک-کیان',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (50,'ممقان','ممقان',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (51,'مهربان','مهربان',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (52,'میانه','میانه',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (53,'نظرکهریزی','نظرکهریزی',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (54,'هادی شهر','هادی-شهر',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (55,'هرگلان','هرگلان',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (56,'هریس','هریس',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (57,'هشترود','هشترود',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (58,'هوراند','هوراند',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (59,'وایقان','وایقان',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (60,'ورزقان','ورزقان',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (61,'یامچی','یامچی',1);
INSERT INTO city(id,title,slug,provinceId) VALUES (62,'ارومیه','ارومیه',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (63,'اشنویه','اشنویه',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (64,'ایواوغلی','ایواوغلی',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (65,'آواجیق','آواجیق',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (66,'باروق','باروق',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (67,'بازرگان','بازرگان',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (68,'بوکان','بوکان',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (69,'پلدشت','پلدشت',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (70,'پیرانشهر','پیرانشهر',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (71,'تازه شهر','تازه-شهر',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (72,'تکاب','تکاب',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (73,'چهاربرج','چهاربرج',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (74,'خوی','خوی',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (75,'دیزج دیز','دیزج-دیز',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (76,'ربط','ربط',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (77,'سردشت','آذربایجان-غربی-سردشت',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (78,'سرو','سرو',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (79,'سلماس','سلماس',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (80,'سیلوانه','سیلوانه',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (81,'سیمینه','سیمینه',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (82,'سیه چشمه','سیه-چشمه',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (83,'شاهین دژ','شاهین-دژ',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (84,'شوط','شوط',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (85,'فیرورق','فیرورق',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (86,'قره ضیاءالدین','قره-ضیاءالدین',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (87,'قطور','قطور',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (88,'قوشچی','قوشچی',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (89,'کشاورز','کشاورز',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (90,'گردکشانه','گردکشانه',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (91,'ماکو','ماکو',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (92,'محمدیار','محمدیار',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (93,'محمودآباد','آذربایجان-غربی-محمودآباد',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (94,'مهاباد','آذربایجان-غربی-مهاباد',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (95,'میاندوآب','میاندوآب',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (96,'میرآباد','میرآباد',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (97,'نالوس','نالوس',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (98,'نقده','نقده',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (99,'نوشین','نوشین',2);
INSERT INTO city(id,title,slug,provinceId) VALUES (100,'اردبیل','اردبیل',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (101,'اصلاندوز','اصلاندوز',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (102,'آبی بیگلو','آبی-بیگلو',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (103,'بیله سوار','بیله-سوار',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (104,'پارس آباد','پارس-آباد',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (105,'تازه کند','تازه-کند',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (106,'تازه کندانگوت','تازه-کندانگوت',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (107,'جعفرآباد','جعفرآباد',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (108,'خلخال','خلخال',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (109,'رضی','رضی',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (110,'سرعین','سرعین',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (111,'عنبران','عنبران',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (112,'فخرآباد','فخرآباد',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (113,'کلور','کلور',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (114,'کوراییم','کوراییم',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (115,'گرمی','گرمی',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (116,'گیوی','گیوی',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (117,'لاهرود','لاهرود',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (118,'مشگین شهر','مشگین-شهر',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (119,'نمین','نمین',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (120,'نیر','اردبیل-نیر',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (121,'هشتجین','هشتجین',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (122,'هیر','هیر',3);
INSERT INTO city(id,title,slug,provinceId) VALUES (123,'ابریشم','ابریشم',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (124,'ابوزیدآباد','ابوزیدآباد',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (125,'اردستان','اردستان',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (126,'اژیه','اژیه',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (127,'اصفهان','اصفهان',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (128,'افوس','افوس',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (129,'انارک','انارک',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (130,'ایمانشهر','ایمانشهر',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (131,'آران وبیدگل','آران-وبیدگل',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (132,'بادرود','بادرود',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (133,'باغ بهادران','باغ-بهادران',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (134,'بافران','بافران',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (135,'برزک','برزک',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (136,'برف انبار','برف-انبار',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (137,'بهاران شهر','بهاران-شهر',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (138,'بهارستان','بهارستان',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (139,'بوئین و میاندشت','بوئین-میاندشت',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (140,'پیربکران','پیربکران',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (141,'تودشک','تودشک',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (142,'تیران','تیران',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (143,'جندق','جندق',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (144,'جوزدان','جوزدان',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (145,'جوشقان و کامو','جوشقان-کامو',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (146,'چادگان','چادگان',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (147,'چرمهین','چرمهین',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (148,'چمگردان','چمگردان',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (149,'حبیب آباد','حبیب-آباد',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (150,'حسن آباد','اصفهان-حسن-آباد',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (151,'حنا','حنا',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (152,'خالدآباد','خالدآباد',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (153,'خمینی شهر','خمینی-شهر',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (154,'خوانسار','خوانسار',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (155,'خور','اصفهان-خور',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (157,'خورزوق','خورزوق',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (158,'داران','داران',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (159,'دامنه','دامنه',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (160,'درچه','درچه',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (161,'دستگرد','دستگرد',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (162,'دهاقان','دهاقان',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (163,'دهق','دهق',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (164,'دولت آباد','اصفهان-دولت-آباد',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (165,'دیزیچه','دیزیچه',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (166,'رزوه','رزوه',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (167,'رضوانشهر','اصفهان-رضوانشهر',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (168,'زاینده رود','زاینده-رود',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (169,'زرین شهر','زرین-شهر',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (170,'زواره','زواره',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (171,'زیباشهر','زیباشهر',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (172,'سده لنجان','سده-لنجان',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (173,'سفیدشهر','سفیدشهر',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (174,'سگزی','سگزی',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (175,'سمیرم','سمیرم',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (176,'شاهین شهر','شاهین-شهر',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (177,'شهرضا','شهرضا',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (178,'طالخونچه','طالخونچه',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (179,'عسگران','عسگران',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (180,'علویجه','علویجه',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (181,'فرخی','فرخی',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (182,'فریدونشهر','فریدونشهر',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (183,'فلاورجان','فلاورجان',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (184,'فولادشهر','فولادشهر',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (185,'قمصر','قمصر',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (186,'قهجاورستان','قهجاورستان',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (187,'قهدریجان','قهدریجان',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (188,'کاشان','کاشان',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (189,'کرکوند','کرکوند',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (190,'کلیشاد و سودرجان','کلیشاد-سودرجان',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (191,'کمشچه','کمشچه',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (192,'کمه','کمه',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (193,'کهریزسنگ','کهریزسنگ',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (194,'کوشک','کوشک',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (195,'کوهپایه','کوهپایه',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (196,'گرگاب','گرگاب',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (197,'گزبرخوار','گزبرخوار',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (198,'گلپایگان','گلپایگان',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (199,'گلدشت','گلدشت',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (200,'گلشهر','گلشهر',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (201,'گوگد','گوگد',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (202,'لای بید','لای-بید',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (203,'مبارکه','مبارکه',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (204,'مجلسی','مجلسی',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (205,'محمدآباد','اصفهان-محمدآباد',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (206,'مشکات','مشکات',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (207,'منظریه','منظریه',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (208,'مهاباد','اصفهان-مهاباد',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (209,'میمه','اصفهان-میمه',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (210,'نائین','نائین',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (211,'نجف آباد','نجف-آباد',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (212,'نصرآباد','اصفهان-نصرآباد',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (213,'نطنز','نطنز',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (214,'نوش آباد','نوش-آباد',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (215,'نیاسر','نیاسر',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (216,'نیک آباد','نیک-آباد',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (217,'هرند','هرند',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (218,'ورزنه','ورزنه',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (219,'ورنامخواست','ورنامخواست',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (220,'وزوان','وزوان',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (221,'ونک','ونک',4);
INSERT INTO city(id,title,slug,provinceId) VALUES (222,'اسارا','اسارا',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (223,'اشتهارد','اشتهارد',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (224,'تنکمان','تنکمان',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (225,'چهارباغ','چهارباغ',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (226,'سعید آباد','سعید-آباد',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (227,'شهر جدید هشتگرد','شهر-جدید-هشتگرد',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (228,'طالقان','طالقان',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (229,'کرج','کرج',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (230,'کمال شهر','کمال-شهر',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (231,'کوهسار','کوهسار',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (232,'گرمدره','گرمدره',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (233,'ماهدشت','ماهدشت',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (234,'محمدشهر','البرز-محمدشهر',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (235,'مشکین دشت','مشکین-دشت',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (236,'نظرآباد','نظرآباد',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (237,'هشتگرد','هشتگرد',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (238,'ارکواز','ارکواز',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (239,'ایلام','ایلام',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (240,'ایوان','ایوان',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (241,'آبدانان','آبدانان',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (242,'آسمان آباد','آسمان-آباد',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (243,'بدره','بدره',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (244,'پهله','پهله',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (245,'توحید','توحید',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (246,'چوار','چوار',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (247,'دره شهر','دره-شهر',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (248,'دلگشا','دلگشا',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (249,'دهلران','دهلران',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (250,'زرنه','زرنه',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (251,'سراب باغ','سراب-باغ',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (252,'سرابله','سرابله',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (253,'صالح آباد','ایلام-صالح-آباد',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (254,'لومار','لومار',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (255,'مهران','مهران',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (256,'مورموری','مورموری',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (257,'موسیان','موسیان',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (258,'میمه','ایلام-میمه',6);
INSERT INTO city(id,title,slug,provinceId) VALUES (259,'امام حسن','امام-حسن',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (260,'انارستان','انارستان',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (261,'اهرم','اهرم',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (262,'آب پخش','آب-پخش',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (263,'آبدان','آبدان',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (264,'برازجان','برازجان',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (265,'بردخون','بردخون',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (266,'بندردیر','بندردیر',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (267,'بندردیلم','بندردیلم',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (268,'بندرریگ','بندرریگ',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (269,'بندرکنگان','بندرکنگان',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (270,'بندرگناوه','بندرگناوه',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (271,'بنک','بنک',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (272,'بوشهر','بوشهر',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (273,'تنگ ارم','تنگ-ارم',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (274,'جم','جم',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (275,'چغادک','چغادک',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (276,'خارک','خارک',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (277,'خورموج','خورموج',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (278,'دالکی','دالکی',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (279,'دلوار','دلوار',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (280,'ریز','ریز',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (281,'سعدآباد','سعدآباد',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (282,'سیراف','سیراف',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (283,'شبانکاره','شبانکاره',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (284,'شنبه','شنبه',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (285,'عسلویه','عسلویه',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (286,'کاکی','کاکی',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (287,'کلمه','کلمه',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (288,'نخل تقی','نخل-تقی',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (289,'وحدتیه','وحدتیه',7);
INSERT INTO city(id,title,slug,provinceId) VALUES (290,'ارجمند','ارجمند',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (291,'اسلامشهر','اسلامشهر',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (292,'اندیشه','اندیشه',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (293,'آبسرد','آبسرد',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (294,'آبعلی','آبعلی',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (295,'باغستان','باغستان',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (296,'باقرشهر','باقرشهر',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (297,'بومهن','بومهن',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (298,'پاکدشت','پاکدشت',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (299,'پردیس','پردیس',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (300,'پیشوا','پیشوا',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (301,'تهران','تهران',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (302,'جوادآباد','جوادآباد',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (303,'چهاردانگه','چهاردانگه',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (304,'حسن آباد','تهران-حسن-آباد',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (305,'دماوند','دماوند',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (306,'دیزین','دیزین',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (307,'شهر ری','شهر-ری',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (308,'رباط کریم','رباط-کریم',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (309,'رودهن','رودهن',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (310,'شاهدشهر','شاهدشهر',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (311,'شریف آباد','شریف-آباد',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (312,'شمشک','شمشک',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (313,'شهریار','شهریار',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (314,'صالح آباد','تهران-صالح-آباد',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (315,'صباشهر','صباشهر',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (316,'صفادشت','صفادشت',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (317,'فردوسیه','فردوسیه',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (318,'فشم','فشم',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (319,'فیروزکوه','فیروزکوه',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (320,'قدس','قدس',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (321,'قرچک','قرچک',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (322,'کهریزک','کهریزک',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (323,'کیلان','کیلان',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (324,'گلستان','شهر-گلستان',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (325,'لواسان','لواسان',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (326,'ملارد','ملارد',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (327,'میگون','میگون',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (328,'نسیم شهر','نسیم-شهر',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (329,'نصیرآباد','نصیرآباد',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (330,'وحیدیه','وحیدیه',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (331,'ورامین','ورامین',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (332,'اردل','اردل',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (333,'آلونی','آلونی',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (334,'باباحیدر','باباحیدر',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (335,'بروجن','بروجن',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (336,'بلداجی','بلداجی',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (337,'بن','بن',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (338,'جونقان','جونقان',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (339,'چلگرد','چلگرد',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (340,'سامان','سامان',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (341,'سفیددشت','سفیددشت',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (342,'سودجان','سودجان',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (343,'سورشجان','سورشجان',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (344,'شلمزار','شلمزار',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (345,'شهرکرد','شهرکرد',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (346,'طاقانک','طاقانک',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (347,'فارسان','فارسان',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (348,'فرادنبه','فرادبنه',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (349,'فرخ شهر','فرخ-شهر',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (350,'کیان','کیان',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (351,'گندمان','گندمان',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (352,'گهرو','گهرو',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (353,'لردگان','لردگان',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (354,'مال خلیفه','مال-خلیفه',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (355,'ناغان','ناغان',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (356,'نافچ','نافچ',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (357,'نقنه','نقنه',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (358,'هفشجان','هفشجان',9);
INSERT INTO city(id,title,slug,provinceId) VALUES (359,'ارسک','ارسک',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (360,'اسدیه','اسدیه',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (361,'اسفدن','اسفدن',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (362,'اسلامیه','اسلامیه',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (363,'آرین شهر','آرین-شهر',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (364,'آیسک','آیسک',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (365,'بشرویه','بشرویه',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (366,'بیرجند','بیرجند',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (367,'حاجی آباد','خراسان-جنوبی-حاجی-آباد',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (368,'خضری دشت بیاض','خضری-دشت-بیاض',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (369,'خوسف','خوسف',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (370,'زهان','زهان',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (371,'سرایان','سرایان',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (372,'سربیشه','سربیشه',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (373,'سه قلعه','سه-قلعه',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (374,'شوسف','شوسف',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (375,'طبس','خراسان-جنوبی-طبس-',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (376,'فردوس','فردوس',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (377,'قاین','قاین',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (378,'قهستان','قهستان',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (379,'محمدشهر','خراسان-جنوبی-محمدشهر',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (380,'مود','مود',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (381,'نهبندان','نهبندان',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (382,'نیمبلوک','نیمبلوک',10);
INSERT INTO city(id,title,slug,provinceId) VALUES (383,'احمدآباد صولت','احمدآباد-صولت',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (384,'انابد','انابد',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (385,'باجگیران','باجگیران',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (386,'باخرز','باخرز',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (387,'بار','بار',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (388,'بایگ','بایگ',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (389,'بجستان','بجستان',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (390,'بردسکن','بردسکن',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (391,'بیدخت','بیدخت',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (392,'تایباد','تایباد',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (393,'تربت جام','تربت-جام',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (394,'تربت حیدریه','تربت-حیدریه',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (395,'جغتای','جغتای',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (396,'جنگل','جنگل',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (397,'چاپشلو','چاپشلو',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (398,'چکنه','چکنه',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (399,'چناران','چناران',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (400,'خرو','خرو',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (401,'خلیل آباد','خلیل-آباد',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (402,'خواف','خواف',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (403,'داورزن','داورزن',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (404,'درگز','درگز',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (405,'در رود','در-رود',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (406,'دولت آباد','خراسان-رضوی-دولت-آباد',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (407,'رباط سنگ','رباط-سنگ',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (408,'رشتخوار','رشتخوار',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (409,'رضویه','رضویه',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (410,'روداب','روداب',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (411,'ریوش','ریوش',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (412,'سبزوار','سبزوار',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (413,'سرخس','سرخس',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (414,'سفیدسنگ','سفیدسنگ',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (415,'سلامی','سلامی',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (416,'سلطان آباد','سلطان-آباد',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (417,'سنگان','سنگان',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (418,'شادمهر','شادمهر',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (419,'شاندیز','شاندیز',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (420,'ششتمد','ششتمد',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (421,'شهرآباد','شهرآباد',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (422,'شهرزو','شهرزو',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (423,'صالح آباد','خراسان-رضوی-صالح-آباد',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (424,'طرقبه','طرقبه',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (425,'عشق آباد','خراسان-رضوی-عشق-آباد',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (426,'فرهادگرد','فرهادگرد',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (427,'فریمان','فریمان',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (428,'فیروزه','فیروزه',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (429,'فیض آباد','فیض-آباد',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (430,'قاسم آباد','قاسم-آباد',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (431,'قدمگاه','قدمگاه',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (432,'قلندرآباد','قلندرآباد',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (433,'قوچان','قوچان',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (434,'کاخک','کاخک',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (435,'کاریز','کاریز',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (436,'کاشمر','کاشمر',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (437,'کدکن','کدکن',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (438,'کلات','کلات',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (439,'کندر','کندر',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (440,'گلمکان','گلمکان',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (441,'گناباد','گناباد',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (442,'لطف آباد','لطف-آباد',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (443,'مزدآوند','مزدآوند',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (444,'مشهد','مشهد',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (445,'ملک آباد','ملک-آباد',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (446,'نشتیفان','نشتیفان',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (447,'نصرآباد','خراسان-رضوی-نصرآباد',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (448,'نقاب','نقاب',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (449,'نوخندان','نوخندان',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (450,'نیشابور','نیشابور',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (451,'نیل شهر','نیل-شهر',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (452,'همت آباد','همت-آباد',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (453,'یونسی','یونسی',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (454,'اسفراین','اسفراین',12);
INSERT INTO city(id,title,slug,provinceId) VALUES (455,'ایور','ایور',12);
INSERT INTO city(id,title,slug,provinceId) VALUES (456,'آشخانه','آشخانه',12);
INSERT INTO city(id,title,slug,provinceId) VALUES (457,'بجنورد','بجنورد',12);
INSERT INTO city(id,title,slug,provinceId) VALUES (458,'پیش قلعه','پیش-قلعه',12);
INSERT INTO city(id,title,slug,provinceId) VALUES (459,'تیتکانلو','تیتکانلو',12);
INSERT INTO city(id,title,slug,provinceId) VALUES (460,'جاجرم','جاجرم',12);
INSERT INTO city(id,title,slug,provinceId) VALUES (461,'حصارگرمخان','حصارگرمخان',12);
INSERT INTO city(id,title,slug,provinceId) VALUES (462,'درق','درق',12);
INSERT INTO city(id,title,slug,provinceId) VALUES (463,'راز','راز',12);
INSERT INTO city(id,title,slug,provinceId) VALUES (464,'سنخواست','سنخواست',12);
INSERT INTO city(id,title,slug,provinceId) VALUES (465,'شوقان','شوقان',12);
INSERT INTO city(id,title,slug,provinceId) VALUES (466,'شیروان','شیروان',12);
INSERT INTO city(id,title,slug,provinceId) VALUES (467,'صفی آباد','خراسان-شمالی-صفی-آباد',12);
INSERT INTO city(id,title,slug,provinceId) VALUES (468,'فاروج','فاروج',12);
INSERT INTO city(id,title,slug,provinceId) VALUES (469,'قاضی','قاضی',12);
INSERT INTO city(id,title,slug,provinceId) VALUES (470,'گرمه','گرمه',12);
INSERT INTO city(id,title,slug,provinceId) VALUES (471,'لوجلی','لوجلی',12);
INSERT INTO city(id,title,slug,provinceId) VALUES (472,'اروندکنار','اروندکنار',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (473,'الوان','الوان',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (474,'امیدیه','امیدیه',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (475,'اندیمشک','اندیمشک',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (476,'اهواز','اهواز',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (477,'ایذه','ایذه',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (478,'آبادان','آبادان',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (479,'آغاجاری','آغاجاری',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (480,'باغ ملک','باغ-ملک',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (481,'بستان','بستان',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (482,'بندرامام خمینی','بندرامام-خمینی',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (483,'بندرماهشهر','بندرماهشهر',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (484,'بهبهان','بهبهان',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (485,'ترکالکی','ترکالکی',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (486,'جایزان','جایزان',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (487,'چمران','چمران',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (488,'چویبده','چویبده',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (489,'حر','حر',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (490,'حسینیه','حسینیه',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (491,'حمزه','حمزه',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (492,'حمیدیه','حمیدیه',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (493,'خرمشهر','خرمشهر',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (494,'دارخوین','دارخوین',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (495,'دزآب','دزآب',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (496,'دزفول','دزفول',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (497,'دهدز','دهدز',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (498,'رامشیر','رامشیر',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (499,'رامهرمز','رامهرمز',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (500,'رفیع','رفیع',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (501,'زهره','زهره',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (502,'سالند','سالند',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (503,'سردشت','خوزستان-سردشت',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (504,'سوسنگرد','سوسنگرد',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (505,'شادگان','شادگان',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (506,'شاوور','شاوور',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (507,'شرافت','شرافت',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (508,'شوش','شوش',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (509,'شوشتر','شوشتر',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (510,'شیبان','شیبان',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (511,'صالح شهر','صالح-شهر',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (512,'صفی آباد','خوزستان-صفی-آباد',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (513,'صیدون','صیدون',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (514,'قلعه تل','قلعه-تل',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (515,'قلعه خواجه','قلعه-خواجه',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (516,'گتوند','گتوند',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (517,'لالی','لالی',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (518,'مسجدسلیمان','مسجدسلیمان',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (520,'ملاثانی','ملاثانی',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (521,'میانرود','میانرود',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (522,'مینوشهر','مینوشهر',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (523,'هفتگل','هفتگل',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (524,'هندیجان','هندیجان',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (525,'هویزه','هویزه',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (526,'ویس','ویس',13);
INSERT INTO city(id,title,slug,provinceId) VALUES (527,'ابهر','ابهر',14);
INSERT INTO city(id,title,slug,provinceId) VALUES (528,'ارمغان خانه','ارمغان-خانه',14);
INSERT INTO city(id,title,slug,provinceId) VALUES (529,'آب بر','آب-بر',14);
INSERT INTO city(id,title,slug,provinceId) VALUES (530,'چورزق','چورزق',14);
INSERT INTO city(id,title,slug,provinceId) VALUES (531,'حلب','حلب',14);
INSERT INTO city(id,title,slug,provinceId) VALUES (532,'خرمدره','خرمدره',14);
INSERT INTO city(id,title,slug,provinceId) VALUES (533,'دندی','دندی',14);
INSERT INTO city(id,title,slug,provinceId) VALUES (534,'زرین آباد','زرین-آباد',14);
INSERT INTO city(id,title,slug,provinceId) VALUES (535,'زرین رود','زرین-رود',14);
INSERT INTO city(id,title,slug,provinceId) VALUES (536,'زنجان','زنجان',14);
INSERT INTO city(id,title,slug,provinceId) VALUES (537,'سجاس','سجاس',14);
INSERT INTO city(id,title,slug,provinceId) VALUES (538,'سلطانیه','سلطانیه',14);
INSERT INTO city(id,title,slug,provinceId) VALUES (539,'سهرورد','سهرورد',14);
INSERT INTO city(id,title,slug,provinceId) VALUES (540,'صائین قلعه','صائین-قلعه',14);
INSERT INTO city(id,title,slug,provinceId) VALUES (541,'قیدار','قیدار',14);
INSERT INTO city(id,title,slug,provinceId) VALUES (542,'گرماب','گرماب',14);
INSERT INTO city(id,title,slug,provinceId) VALUES (543,'ماه نشان','ماه-نشان',14);
INSERT INTO city(id,title,slug,provinceId) VALUES (544,'هیدج','هیدج',14);
INSERT INTO city(id,title,slug,provinceId) VALUES (545,'امیریه','امیریه',15);
INSERT INTO city(id,title,slug,provinceId) VALUES (546,'ایوانکی','ایوانکی',15);
INSERT INTO city(id,title,slug,provinceId) VALUES (547,'آرادان','آرادان',15);
INSERT INTO city(id,title,slug,provinceId) VALUES (548,'بسطام','بسطام',15);
INSERT INTO city(id,title,slug,provinceId) VALUES (549,'بیارجمند','بیارجمند',15);
INSERT INTO city(id,title,slug,provinceId) VALUES (550,'دامغان','دامغان',15);
INSERT INTO city(id,title,slug,provinceId) VALUES (551,'درجزین','درجزین',15);
INSERT INTO city(id,title,slug,provinceId) VALUES (552,'دیباج','دیباج',15);
INSERT INTO city(id,title,slug,provinceId) VALUES (553,'سرخه','سرخه',15);
INSERT INTO city(id,title,slug,provinceId) VALUES (554,'سمنان','سمنان',15);
INSERT INTO city(id,title,slug,provinceId) VALUES (555,'شاهرود','شاهرود',15);
INSERT INTO city(id,title,slug,provinceId) VALUES (556,'شهمیرزاد','شهمیرزاد',15);
INSERT INTO city(id,title,slug,provinceId) VALUES (557,'کلاته خیج','کلاته-خیج',15);
INSERT INTO city(id,title,slug,provinceId) VALUES (558,'گرمسار','گرمسار',15);
INSERT INTO city(id,title,slug,provinceId) VALUES (559,'مجن','مجن',15);
INSERT INTO city(id,title,slug,provinceId) VALUES (560,'مهدی شهر','مهدی-شهر',15);
INSERT INTO city(id,title,slug,provinceId) VALUES (561,'میامی','میامی',15);
INSERT INTO city(id,title,slug,provinceId) VALUES (562,'ادیمی','ادیمی',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (563,'اسپکه','اسپکه',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (564,'ایرانشهر','ایرانشهر',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (565,'بزمان','بزمان',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (566,'بمپور','بمپور',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (567,'بنت','بنت',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (568,'بنجار','بنجار',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (569,'پیشین','پیشین',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (570,'جالق','جالق',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (571,'چابهار','چابهار',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (572,'خاش','خاش',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (573,'دوست محمد','دوست-محمد',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (574,'راسک','راسک',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (575,'زابل','زابل',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (576,'زابلی','زابلی',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (577,'زاهدان','زاهدان',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (578,'زهک','زهک',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (579,'سراوان','سراوان',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (580,'سرباز','سرباز',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (581,'سوران','سوران',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (582,'سیرکان','سیرکان',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (583,'علی اکبر','علی-اکبر',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (584,'فنوج','فنوج',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (585,'قصرقند','قصرقند',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (586,'کنارک','کنارک',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (587,'گشت','گشت',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (588,'گلمورتی','گلمورتی',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (589,'محمدان','محمدان',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (590,'محمدآباد','سیستان-و-بلوچستان-محمدآباد',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (591,'محمدی','محمدی',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (592,'میرجاوه','میرجاوه',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (593,'نصرت آباد','نصرت-آباد',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (594,'نگور','نگور',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (595,'نوک آباد','نوک-آباد',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (596,'نیک شهر','نیک-شهر',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (597,'هیدوچ','هیدوچ',16);
INSERT INTO city(id,title,slug,provinceId) VALUES (598,'اردکان','فارس-اردکان',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (599,'ارسنجان','ارسنجان',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (600,'استهبان','استهبان',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (601,'اشکنان','اشکنان',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (602,'افزر','افزر',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (603,'اقلید','اقلید',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (604,'امام شهر','امام-شهر',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (605,'اهل','اهل',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (606,'اوز','اوز',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (607,'ایج','ایج',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (608,'ایزدخواست','ایزدخواست',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (609,'آباده','آباده',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (610,'آباده طشک','آباده-طشک',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (611,'باب انار','باب-انار',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (612,'بالاده','فارس-بالاده',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (613,'بنارویه','بنارویه',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (614,'بهمن','بهمن',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (615,'بوانات','بوانات',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (616,'بیرم','بیرم',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (617,'بیضا','بیضا',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (618,'جنت شهر','جنت-شهر',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (619,'جهرم','جهرم',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (620,'جویم','جویم',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (621,'زرین دشت','زرین-دشت',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (622,'حسن آباد','فارس-حسن-آباد',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (623,'خان زنیان','خان-زنیان',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (624,'خاوران','خاوران',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (625,'خرامه','خرامه',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (626,'خشت','خشت',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (627,'خنج','خنج',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (628,'خور','فارس-خور',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (629,'داراب','داراب',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (630,'داریان','داریان',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (631,'دبیران','دبیران',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (632,'دژکرد','دژکرد',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (633,'دهرم','دهرم',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (634,'دوبرجی','دوبرجی',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (635,'رامجرد','رامجرد',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (636,'رونیز','رونیز',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (637,'زاهدشهر','زاهدشهر',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (638,'زرقان','زرقان',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (639,'سده','سده',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (640,'سروستان','سروستان',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (641,'سعادت شهر','سعادت-شهر',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (642,'سورمق','سورمق',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (643,'سیدان','سیدان',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (644,'ششده','ششده',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (645,'شهرپیر','شهرپیر',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (646,'شهرصدرا','شهرصدرا',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (647,'شیراز','شیراز',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (648,'صغاد','صغاد',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (649,'صفاشهر','صفاشهر',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (650,'علامرودشت','علامرودشت',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (651,'فدامی','فدامی',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (652,'فراشبند','فراشبند',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (653,'فسا','فسا',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (654,'فیروزآباد','فارس-فیروزآباد',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (655,'قائمیه','قائمیه',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (656,'قادرآباد','قادرآباد',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (657,'قطب آباد','قطب-آباد',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (658,'قطرویه','قطرویه',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (659,'قیر','قیر',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (660,'کارزین (فتح آباد)','کارزین-فتح-آباد',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (661,'کازرون','کازرون',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (662,'کامفیروز','کامفیروز',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (663,'کره ای','کره-ای',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (664,'کنارتخته','کنارتخته',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (665,'کوار','کوار',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (666,'گراش','گراش',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (667,'گله دار','گله-دار',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (668,'لار','لار',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (669,'لامرد','لامرد',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (670,'لپویی','لپویی',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (671,'لطیفی','لطیفی',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (672,'مبارک آباددیز','مبارک-آباددیز',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (673,'مرودشت','مرودشت',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (674,'مشکان','مشکان',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (675,'مصیری','مصیری',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (676,'مهر','مهر',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (677,'میمند','میمند',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (678,'نوبندگان','نوبندگان',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (679,'نوجین','نوجین',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (680,'نودان','نودان',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (681,'نورآباد','فارس-نورآباد',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (682,'نی ریز','نی-ریز',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (683,'وراوی','وراوی',17);
INSERT INTO city(id,title,slug,provinceId) VALUES (684,'ارداق','ارداق',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (685,'اسفرورین','اسفرورین',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (686,'اقبالیه','اقبالیه',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (687,'الوند','الوند',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (688,'آبگرم','آبگرم',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (689,'آبیک','آبیک',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (690,'آوج','آوج',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (691,'بوئین زهرا','بوئین-زهرا',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (692,'بیدستان','بیدستان',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (693,'تاکستان','تاکستان',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (694,'خاکعلی','خاکعلی',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (695,'خرمدشت','خرمدشت',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (696,'دانسفهان','دانسفهان',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (697,'رازمیان','رازمیان',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (698,'سگزآباد','سگزآباد',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (699,'سیردان','سیردان',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (700,'شال','شال',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (701,'شریفیه','شریفیه',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (702,'ضیاآباد','ضیاآباد',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (703,'قزوین','قزوین',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (704,'کوهین','کوهین',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (705,'محمدیه','محمدیه',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (706,'محمودآباد نمونه','محمودآباد-نمونه',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (707,'معلم کلایه','معلم-کلایه',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (708,'نرجه','نرجه',18);
INSERT INTO city(id,title,slug,provinceId) VALUES (709,'جعفریه','جعفریه',19);
INSERT INTO city(id,title,slug,provinceId) VALUES (710,'دستجرد','دستجرد',19);
INSERT INTO city(id,title,slug,provinceId) VALUES (711,'سلفچگان','سلفچگان',19);
INSERT INTO city(id,title,slug,provinceId) VALUES (712,'قم','قم',19);
INSERT INTO city(id,title,slug,provinceId) VALUES (713,'قنوات','قنوات',19);
INSERT INTO city(id,title,slug,provinceId) VALUES (714,'کهک','کهک',19);
INSERT INTO city(id,title,slug,provinceId) VALUES (715,'آرمرده','آرمرده',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (716,'بابارشانی','بابارشانی',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (717,'بانه','بانه',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (718,'بلبان آباد','بلبان-آباد',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (719,'بوئین سفلی','بوئین-سفلی',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (720,'بیجار','بیجار',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (721,'چناره','چناره',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (722,'دزج','دزج',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (723,'دلبران','دلبران',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (724,'دهگلان','دهگلان',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (725,'دیواندره','دیواندره',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (726,'زرینه','زرینه',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (727,'سروآباد','سروآباد',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (728,'سریش آباد','سریش-آباد',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (729,'سقز','سقز',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (730,'سنندج','سنندج',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (731,'شویشه','شویشه',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (732,'صاحب','صاحب',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (733,'قروه','قروه',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (734,'کامیاران','کامیاران',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (735,'کانی دینار','کانی-دینار',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (736,'کانی سور','کانی-سور',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (737,'مریوان','مریوان',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (738,'موچش','موچش',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (739,'یاسوکند','یاسوکند',20);
INSERT INTO city(id,title,slug,provinceId) VALUES (740,'اختیارآباد','اختیارآباد',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (741,'ارزوئیه','ارزوئیه',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (742,'امین شهر','امین-شهر',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (743,'انار','انار',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (744,'اندوهجرد','اندوهجرد',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (745,'باغین','باغین',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (746,'بافت','بافت',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (747,'بردسیر','بردسیر',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (748,'بروات','بروات',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (749,'بزنجان','بزنجان',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (750,'بم','بم',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (751,'بهرمان','بهرمان',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (752,'پاریز','پاریز',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (753,'جبالبارز','جبالبارز',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (754,'جوپار','جوپار',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (755,'جوزم','جوزم',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (756,'جیرفت','جیرفت',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (757,'چترود','چترود',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (758,'خاتون آباد','خاتون-آباد',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (759,'خانوک','خانوک',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (760,'خورسند','خورسند',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (761,'درب بهشت','درب-بهشت',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (762,'دهج','دهج',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (763,'رابر','رابر',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (764,'راور','راور',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (765,'راین','راین',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (766,'رفسنجان','رفسنجان',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (767,'رودبار','کرمان-رودبار',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (768,'ریحان شهر','ریحان-شهر',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (769,'زرند','زرند',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (770,'زنگی آباد','زنگی-آباد',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (771,'زیدآباد','زیدآباد',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (772,'سیرجان','سیرجان',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (773,'شهداد','شهداد',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (774,'شهربابک','شهربابک',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (775,'صفائیه','صفائیه',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (776,'عنبرآباد','عنبرآباد',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (777,'فاریاب','فاریاب',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (778,'فهرج','فهرج',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (779,'قلعه گنج','قلعه-گنج',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (780,'کاظم آباد','کاظم-آباد',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (781,'کرمان','کرمان',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (782,'کشکوئیه','کشکوئیه',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (783,'کهنوج','کهنوج',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (784,'کوهبنان','کوهبنان',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (785,'کیانشهر','کیانشهر',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (786,'گلباف','گلباف',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (787,'گلزار','گلزار',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (788,'لاله زار','لاله-زار',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (789,'ماهان','ماهان',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (790,'محمدآباد','کرمان-محمدآباد',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (791,'محی آباد','محی-آباد',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (792,'مردهک','مردهک',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (793,'مس سرچشمه','مس-سرچشمه',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (794,'منوجان','منوجان',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (795,'نجف شهر','نجف-شهر',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (796,'نرماشیر','نرماشیر',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (797,'نظام شهر','نظام-شهر',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (798,'نگار','نگار',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (799,'نودژ','نودژ',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (800,'هجدک','هجدک',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (801,'یزدان شهر','یزدان-شهر',21);
INSERT INTO city(id,title,slug,provinceId) VALUES (802,'ازگله','ازگله',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (803,'اسلام آباد غرب','اسلام-آباد-غرب',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (804,'باینگان','باینگان',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (805,'بیستون','بیستون',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (806,'پاوه','پاوه',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (807,'تازه آباد','تازه-آباد',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (808,'جوان رود','جوان-رود',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (809,'حمیل','حمیل',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (810,'ماهیدشت','ماهیدشت',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (811,'روانسر','روانسر',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (812,'سرپل ذهاب','سرپل-ذهاب',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (813,'سرمست','سرمست',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (814,'سطر','سطر',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (815,'سنقر','سنقر',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (816,'سومار','سومار',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (817,'شاهو','شاهو',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (818,'صحنه','صحنه',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (819,'قصرشیرین','قصرشیرین',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (820,'کرمانشاه','کرمانشاه',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (821,'کرندغرب','کرندغرب',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (822,'کنگاور','کنگاور',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (823,'کوزران','کوزران',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (824,'گهواره','گهواره',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (825,'گیلانغرب','گیلانغرب',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (826,'میان راهان','میان-راهان',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (827,'نودشه','نودشه',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (828,'نوسود','نوسود',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (829,'هرسین','هرسین',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (830,'هلشی','هلشی',22);
INSERT INTO city(id,title,slug,provinceId) VALUES (831,'باشت','باشت',23);
INSERT INTO city(id,title,slug,provinceId) VALUES (832,'پاتاوه','پاتاوه',23);
INSERT INTO city(id,title,slug,provinceId) VALUES (833,'چرام','چرام',23);
INSERT INTO city(id,title,slug,provinceId) VALUES (834,'چیتاب','چیتاب',23);
INSERT INTO city(id,title,slug,provinceId) VALUES (835,'دهدشت','دهدشت',23);
INSERT INTO city(id,title,slug,provinceId) VALUES (836,'دوگنبدان','دوگنبدان',23);
INSERT INTO city(id,title,slug,provinceId) VALUES (837,'دیشموک','دیشموک',23);
INSERT INTO city(id,title,slug,provinceId) VALUES (838,'سوق','سوق',23);
INSERT INTO city(id,title,slug,provinceId) VALUES (839,'سی سخت','سی-سخت',23);
INSERT INTO city(id,title,slug,provinceId) VALUES (840,'قلعه رئیسی','قلعه-رئیسی',23);
INSERT INTO city(id,title,slug,provinceId) VALUES (841,'گراب سفلی','گراب-سفلی',23);
INSERT INTO city(id,title,slug,provinceId) VALUES (842,'لنده','لنده',23);
INSERT INTO city(id,title,slug,provinceId) VALUES (843,'لیکک','لیکک',23);
INSERT INTO city(id,title,slug,provinceId) VALUES (844,'مادوان','مادوان',23);
INSERT INTO city(id,title,slug,provinceId) VALUES (845,'مارگون','مارگون',23);
INSERT INTO city(id,title,slug,provinceId) VALUES (846,'یاسوج','یاسوج',23);
INSERT INTO city(id,title,slug,provinceId) VALUES (847,'انبارآلوم','انبارآلوم',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (848,'اینچه برون','اینچه-برون',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (849,'آزادشهر','آزادشهر',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (850,'آق قلا','آق-قلا',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (851,'بندرترکمن','بندرترکمن',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (852,'بندرگز','بندرگز',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (853,'جلین','جلین',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (854,'خان ببین','خان-ببین',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (855,'دلند','دلند',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (856,'رامیان','رامیان',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (857,'سرخنکلاته','سرخنکلاته',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (858,'سیمین شهر','سیمین-شهر',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (859,'علی آباد کتول','علی-آباد-کتول',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (860,'فاضل آباد','فاضل-آباد',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (861,'کردکوی','کردکوی',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (862,'کلاله','کلاله',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (863,'گالیکش','گالیکش',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (864,'گرگان','گرگان',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (865,'گمیش تپه','گمیش-تپه',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (866,'گنبدکاووس','گنبدکاووس',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (867,'مراوه','مراوه',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (868,'مینودشت','مینودشت',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (869,'نگین شهر','نگین-شهر',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (870,'نوده خاندوز','نوده-خاندوز',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (871,'نوکنده','نوکنده',24);
INSERT INTO city(id,title,slug,provinceId) VALUES (872,'ازنا','ازنا',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (873,'اشترینان','اشترینان',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (874,'الشتر','الشتر',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (875,'الیگودرز','الیگودرز',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (876,'بروجرد','بروجرد',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (877,'پلدختر','پلدختر',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (878,'چالانچولان','چالانچولان',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (879,'چغلوندی','چغلوندی',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (880,'چقابل','چقابل',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (881,'خرم آباد','لرستان-خرم-آباد',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (882,'درب گنبد','درب-گنبد',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (883,'دورود','دورود',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (884,'زاغه','زاغه',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (885,'سپیددشت','سپیددشت',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (886,'سراب دوره','سراب-دوره',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (887,'فیروزآباد','لرستان-فیروزآباد',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (888,'کونانی','کونانی',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (889,'کوهدشت','کوهدشت',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (890,'گراب','گراب',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (891,'معمولان','معمولان',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (892,'مومن آباد','مومن-آباد',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (893,'نورآباد','لرستان-نورآباد',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (894,'ویسیان','ویسیان',25);
INSERT INTO city(id,title,slug,provinceId) VALUES (895,'احمدسرگوراب','احمدسرگوراب',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (896,'اسالم','اسالم',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (897,'اطاقور','اطاقور',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (898,'املش','املش',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (899,'آستارا','آستارا',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (900,'آستانه اشرفیه','آستانه-اشرفیه',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (901,'بازار جمعه','بازار-جمعه',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (902,'بره سر','بره-سر',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (903,'بندرانزلی','بندرانزلی',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (906,'پره سر','پره-سر',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (907,'تالش','تالش',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (908,'توتکابن','توتکابن',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (909,'جیرنده','جیرنده',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (910,'چابکسر','چابکسر',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (911,'چاف و چمخاله','چاف-و-چمخاله',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (912,'چوبر','چوبر',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (913,'حویق','حویق',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (914,'خشکبیجار','خشکبیجار',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (915,'خمام','خمام',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (916,'دیلمان','دیلمان',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (917,'رانکوه','رانکوه',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (918,'رحیم آباد','رحیم-آباد',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (919,'رستم آباد','رستم-آباد',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (920,'رشت','رشت',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (921,'رضوانشهر','گیلان-رضوانشهر',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (922,'رودبار','گیلان-رودبار',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (923,'رودبنه','رودبنه',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (924,'رودسر','رودسر',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (925,'سنگر','سنگر',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (926,'سیاهکل','سیاهکل',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (927,'شفت','شفت',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (928,'شلمان','شلمان',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (929,'صومعه سرا','صومعه-سرا',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (930,'فومن','فومن',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (931,'کلاچای','کلاچای',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (932,'کوچصفهان','کوچصفهان',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (933,'کومله','کومله',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (934,'کیاشهر','کیاشهر',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (935,'گوراب زرمیخ','گوراب-زرمیخ',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (936,'لاهیجان','لاهیجان',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (937,'لشت نشا','لشت-نشا',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (938,'لنگرود','لنگرود',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (939,'لوشان','لوشان',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (940,'لولمان','لولمان',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (941,'لوندویل','لوندویل',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (942,'لیسار','لیسار',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (943,'ماسال','ماسال',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (944,'ماسوله','ماسوله',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (945,'مرجقل','مرجقل',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (946,'منجیل','منجیل',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (947,'واجارگاه','واجارگاه',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (948,'امیرکلا','امیرکلا',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (949,'ایزدشهر','ایزدشهر',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (950,'آلاشت','آلاشت',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (951,'آمل','آمل',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (952,'بابل','بابل',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (953,'بابلسر','بابلسر',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (954,'بلده','مازندران-بلده',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (955,'بهشهر','بهشهر',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (956,'بهنمیر','بهنمیر',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (957,'پل سفید','پل-سفید',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (958,'تنکابن','تنکابن',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (959,'جویبار','جویبار',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (960,'چالوس','چالوس',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (961,'چمستان','چمستان',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (962,'خرم آباد','مازندران-خرم-آباد',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (963,'خلیل شهر','خلیل-شهر',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (964,'خوش رودپی','خوش-رودپی',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (965,'دابودشت','دابودشت',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (966,'رامسر','رامسر',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (967,'رستمکلا','رستمکلا',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (968,'رویان','رویان',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (969,'رینه','رینه',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (970,'زرگرمحله','زرگرمحله',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (971,'زیرآب','زیرآب',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (972,'ساری','ساری',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (973,'سرخرود','سرخرود',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (974,'سلمان شهر','سلمان-شهر',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (975,'سورک','سورک',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (976,'شیرگاه','شیرگاه',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (977,'شیرود','شیرود',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (978,'عباس آباد','عباس-آباد',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (979,'فریدونکنار','فریدونکنار',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (980,'فریم','فریم',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (981,'قائم شهر','قائم-شهر',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (982,'کتالم','کتالم',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (983,'کلارآباد','کلارآباد',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (984,'کلاردشت','کلاردشت',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (985,'کله بست','کله-بست',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (986,'کوهی خیل','کوهی-خیل',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (987,'کیاسر','کیاسر',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (988,'کیاکلا','کیاکلا',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (989,'گتاب','گتاب',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (990,'گزنک','گزنک',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (991,'گلوگاه','گلوگاه',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (992,'محمودآباد','مازندران-محمودآباد',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (993,'مرزن آباد','مرزن-آباد',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (994,'مرزیکلا','مرزیکلا',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (995,'نشتارود','نشتارود',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (996,'نکا','نکا',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (997,'نور','نور',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (998,'نوشهر','نوشهر',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (999,'اراک','اراک',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1000,'آستانه','آستانه',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1001,'آشتیان','آشتیان',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1002,'پرندک','پرندک',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1003,'تفرش','تفرش',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1004,'توره','توره',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1005,'جاورسیان','جاورسیان',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1006,'خشکرود','خشکرود',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1007,'خمین','خمین',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1008,'خنداب','خنداب',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1009,'داودآباد','داودآباد',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1010,'دلیجان','دلیجان',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1011,'رازقان','رازقان',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1012,'زاویه','زاویه',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1013,'ساروق','ساروق',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1014,'ساوه','ساوه',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1015,'سنجان','سنجان',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1016,'شازند','شازند',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1017,'غرق آباد','غرق-آباد',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1018,'فرمهین','فرمهین',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1019,'قورچی باشی','قورچی-باشی',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1020,'کرهرود','کرهرود',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1021,'کمیجان','کمیجان',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1022,'مامونیه','مامونیه',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1023,'محلات','محلات',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1024,'مهاجران','مهاجران',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1025,'میلاجرد','میلاجرد',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1026,'نراق','نراق',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1027,'نوبران','نوبران',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1028,'نیمور','نیمور',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1029,'هندودر','هندودر',28);
INSERT INTO city(id,title,slug,provinceId) VALUES (1030,'ابوموسی','ابوموسی',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1031,'بستک','بستک',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1032,'بندرجاسک','بندرجاسک',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1033,'بندرچارک','بندرچارک',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1034,'بندرخمیر','بندرخمیر',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1035,'بندرعباس','بندرعباس',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1036,'بندرلنگه','بندرلنگه',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1037,'بیکا','بیکا',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1038,'پارسیان','پارسیان',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1039,'تخت','تخت',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1040,'جناح','جناح',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1041,'حاجی آباد','هرمزگان-حاجی-آباد',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1042,'درگهان','درگهان',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1043,'دهبارز','دهبارز',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1044,'رویدر','رویدر',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1045,'زیارتعلی','زیارتعلی',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1046,'سردشت','هرمزگان-سردشت',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1047,'سندرک','سندرک',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1048,'سوزا','سوزا',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1049,'سیریک','سیریک',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1050,'فارغان','فارغان',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1051,'فین','فین',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1052,'قشم','قشم',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1053,'قلعه قاضی','قلعه-قاضی',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1054,'کنگ','کنگ',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1055,'کوشکنار','کوشکنار',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1056,'کیش','کیش',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1057,'گوهران','گوهران',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1058,'میناب','میناب',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1059,'هرمز','هرمز',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1060,'هشتبندی','هشتبندی',29);
INSERT INTO city(id,title,slug,provinceId) VALUES (1061,'ازندریان','ازندریان',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1062,'اسدآباد','اسدآباد',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1063,'برزول','برزول',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1064,'بهار','بهار',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1065,'تویسرکان','تویسرکان',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1066,'جورقان','جورقان',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1067,'جوکار','جوکار',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1068,'دمق','دمق',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1069,'رزن','رزن',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1070,'زنگنه','زنگنه',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1071,'سامن','سامن',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1072,'سرکان','سرکان',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1073,'شیرین سو','شیرین-سو',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1074,'صالح آباد','همدان-صالح-آباد',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1075,'فامنین','فامنین',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1076,'فرسفج','فرسفج',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1077,'فیروزان','فیروزان',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1078,'قروه درجزین','قروه-درجزین',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1079,'قهاوند','قهاوند',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1080,'کبودر آهنگ','کبودر-آهنگ',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1081,'گل تپه','گل-تپه',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1082,'گیان','گیان',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1083,'لالجین','لالجین',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1084,'مریانج','مریانج',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1085,'ملایر','ملایر',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1086,'نهاوند','نهاوند',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1087,'همدان','همدان',30);
INSERT INTO city(id,title,slug,provinceId) VALUES (1088,'ابرکوه','ابرکوه',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1089,'احمدآباد','احمدآباد',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1090,'اردکان','یزد-اردکان',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1091,'اشکذر','اشکذر',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1092,'بافق','بافق',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1093,'بفروئیه','بفروئیه',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1094,'بهاباد','بهاباد',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1095,'تفت','تفت',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1096,'حمیدیا','حمیدیا',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1097,'خضرآباد','خضرآباد',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1098,'دیهوک','دیهوک',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1099,'زارچ','زارچ',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1100,'شاهدیه','شاهدیه',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1101,'طبس','یزد-طبس',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1103,'عقدا','عقدا',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1104,'مروست','مروست',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1105,'مهردشت','مهردشت',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1106,'مهریز','مهریز',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1107,'میبد','میبد',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1108,'ندوشن','ندوشن',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1109,'نیر','یزد-نیر',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1110,'هرات','هرات',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1111,'یزد','یزد',31);
INSERT INTO city(id,title,slug,provinceId) VALUES (1116,'پرند','پرند',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (1117,'فردیس','فردیس',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (1118,'مارلیک','مارلیک',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (1119,'سادات شهر','سادات-شهر',27);
INSERT INTO city(id,title,slug,provinceId) VALUES (1121,'زیباکنار','زیباکنار',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (1135,'کردان','کردان',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (1137,'ساوجبلاغ','ساوجبلاغ',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (1138,'تهران دشت','تهران-دشت',5);
INSERT INTO city(id,title,slug,provinceId) VALUES (1150,'گلبهار','گلبهار',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (1153,'قیامدشت','قیامدشت',8);
INSERT INTO city(id,title,slug,provinceId) VALUES (1155,'بینالود','بینالود',11);
INSERT INTO city(id,title,slug,provinceId) VALUES (1159,'پیربازار','پیربازار',26);
INSERT INTO city(id,title,slug,provinceId) VALUES (1160,'رضوانشهر','رضوانشهر',31);
